accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page='accounts:login'), name='logout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('accounts/', include('accounts.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api-docs/', include_docs_urls(title='api sample')),
    path('swagger/api.json', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/api/v1/urls.py
from .views import TaskViewSet
from rest_framework.routers import DefaultRouter

app_name = 'api-v1'

router = DefaultRouter()
router.register('task', TaskViewSet, basename='task')
urlpatterns = router.urls

todo/urls.py
from django.urls import path, include
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='task-list'),
    path('create/', views.TaskCreateView.as_view(), name='task-create'),
    path('delete/<int:pk>/', views.TaskDeleteView.as_view(), name='task-delete'),
    path('finish/<int:pk>/', views.TaskCompleteView.as_view(), name='task-complete'),
    path('edit/<int:pk>/', views.TaskEditView.as_view(), name='task-edit'),
    path('api/v1/', include('todo.api.v1.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    is_completed = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def get_absolute_api_url(self):
        return reverse('todo:api-v1:task-detail', kwargs={'pk': self.pk})

accounts/views.py
from django.shortcuts import redirect
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

class LoginView(LoginView):
    template_name = 'accounts/login.html'
    fields = ('username', 'password')
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy("todo:task-list")

class RegisterView(CreateView):
    template_name = 'accounts/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy("accounts:login")

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')
        return super().get(request, *args, **kwargs)

todo/api/v1/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend
from ...models import Task
from .serializers import TaskSerializer
from .paginations import DefaultPagination

class TaskViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = TaskSerializer
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ['is_completed']
    search_fields = ['title']
    ordering_fields = ['created_date', 'updated_date']
    pagination_class = DefaultPagination

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user)

todo/views.py
# from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Task

class TaskListView(LoginRequiredMixin, ListView):
    template_name = 'todo/task_list.html'

    context_object_name = 'tasks'

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user)


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    fields = ('title',)
    success_url = '/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = '/'


class TaskCompleteView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ('is_completed',)
    success_url = '/'

class TaskEditView(LoginRequiredMixin, UpdateView):
    template_name = 'todo/task_edit.html'
    model = Task
    fields = ('title',)
    success_url = '/'

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        pk = self.kwargs.get(self.pk_url_kwarg)
        task = Task.objects.filter(user= self.request.user, id=pk)
        context['tasks'] = task
        return context

templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Login</h2>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
    </form>
</body>
</html>

templates/accounts/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>
    <h2>Register</h2>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
    </form>
</body>
</html>

templates/todo/task_edit.html
<section class="vh-100" style="background-color: #eee;">
	<div class="container py-5 h-100">
	  <div class="row d-flex justify-content-center align-items-center h-100">
		<div class="col col-lg-9 col-xl-7">
		  <div class="card rounded-3">
			<div class="card-body p-4">
  
			  <h4 class="text-center my-3 pb-3">To Do App</h4>
  
			  <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2" method="POST" action="{% url 'todo:task-edit' pk=task.id %}">
				{% csrf_token %}
				<div class="col-12">
				  <div class="form-outline">
					<input type="text" name="title" id="form1" class="form-control" placeholder="Enter task title" />
					<label class="form-label" for="form1">Enter a task here</label>
				  </div>
				</div>
  
				<div class="col-12">
				  <button type="submit" class="btn btn-primary">Save</button>
				</div>
			  </form>
  
			  <table class="table mb-4">
				<thead>
				  <tr>
					<th scope="col">No.</th>
					<th scope="col">Todo item</th>
					<th scope="col">Status</th>
					<th scope="col">Actions</th>
				  </tr>
				</thead>
				<tbody>
				  <tr>
					<th scope="row">1</th>
					<td>{{task.title}}</td>
					{% if task.is_completed %}
					<td>Finished</td>
					{% else %}
					<td>In progress</td> 
					{% endif %}
				  </tr>
				</tbody>
			  </table>
  
			</div>
		  </div>
		</div>
	  </div>
	</div>
  </section>
  <br><br><br>
  <a href="{% url 'todo:task-list' %}"> 
    HOME PAGE
  </a>

templates/todo/task_list.html
<a href="{% url 'accounts:logout' %}">logout</a>
<section class="vh-100" style="background-color: #eee;">
	<div class="container py-5 h-100">
	  <div class="row d-flex justify-content-center align-items-center h-100">
		<div class="col col-lg-9 col-xl-7">
		  <div class="card rounded-3">
			<div class="card-body p-4">
  
			  <h4 class="text-center my-3 pb-3">To Do App</h4>
  
			  <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2" method="POST" action="{% url 'todo:task-create' %}">
				{% csrf_token %}
				<div class="col-12">
				  <div class="form-outline">
					<input type="text" name="title" id="form1" class="form-control" placeholder="Enter task title" />
					<label class="form-label" for="form1">Enter a task here</label>
				  </div>
				</div>
  
				<div class="col-12">
				  <button type="submit" class="btn btn-primary">Save</button>
				</div>
			  </form>
  
			  <table class="table mb-4">
				<thead>
				  <tr>
					<th scope="col">No.</th>
					<th scope="col">Todo item</th>
					<th scope="col">Status</th>
					<th scope="col">Actions</th>
				  </tr>
				</thead>
				<tbody>
				  {% for task in tasks %}
				  <tr>
					<th scope="row">{{forloop.counter}}</th>
					<td>{{task.title}}</td>
					{% if task.is_completed %}
					<td>Finished</td>
					<td>
						<form method="POST" action="{% url 'todo:task-delete' pk=task.id %}" style="margin:auto; display: block;">
							{% csrf_token %}
							<button type="submit" class="btn btn-danger" style="margin:auto; display: block;">Delete</button>
						</form>
					</td>
					<td>
						<form method="POST" action="{% url 'todo:task-edit' pk=task.id %}" style="margin:auto; display: block;">
							{% csrf_token %}
							<button type="submit" class="btn btn-danger" style="margin:auto; display: block;">Edit</button>
						</form>
					</td> 
					{% else %}
					<td>In progress</td>
					<td>
						<form method="POST" action="{% url 'todo:task-delete' pk=task.id %}" style="margin:auto; display: block;">
							{% csrf_token %}
							<button type="submit" class="btn btn-danger" style="margin:auto; display: block;">Delete</button>
						</form>
					</td>
					<td>
						<form method="POST" action="{% url 'todo:task-edit' pk=task.id %}" style="margin:auto; display: block;">
							{% csrf_token %}
							<button type="submit" class="btn btn-danger" style="margin:auto; display: block;">Edit</button>
						</form>
					</td> 
					<td>
						<form method="POST" action="{% url 'todo:task-complete' pk=task.id %}" style="margin:auto; display: block;">
							{% csrf_token %}
							<input type="hidden" name="is_completed" value="True">
							<button type="submit" class="btn btn-success ms-1" style="margin:auto; display: block;">Finished</button>
						</form>
					</td>
					{% endif %}
				  </tr>
				  {% endfor %}
				</tbody>
			  </table>
  
			</div>
		  </div>
		</div>
	  </div>
	</div>
  </section>